In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
data_df = pd.read_csv("./SpotifyTopSongsByCountry - May 2020.csv")

In [7]:
data_df.shape

(3150, 8)

In [17]:
data_df.head(60)

,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration
0,Global,Global,1,Rain On Me (with Ariana Grande),"Lady Gaga, Ariana Grande",Rain On Me (with Ariana Grande),0,3:02
1,Global,Global,2,Blinding Lights,The Weeknd,After Hours,0,3:20
2,Global,Global,3,ROCKSTAR (feat. Roddy Ricch),"DaBaby, Roddy Ricch",BLAME IT ON BABY,1,3:01
3,Global,Global,4,Roses - Imanbek Remix,"SAINt JHN, Imanbek",Roses (Imanbek Remix),1,2:56
4,Global,Global,5,Toosie Slide,Drake,Dark Lane Demo Tapes,1,4:07
5,Global,Global,6,death bed (coffee for your head) (feat. beabad...,"Powfu, beabadoobee",death bed (coffee for your head) (feat. beabad...,0,2:53
6,Global,Global,7,THE SCOTTS,"THE SCOTTS, Travis Scott, Kid Cudi",THE SCOTTS,1,2:45
7,Global,Global,8,Don't Start Now,Dua Lipa,Future Nostalgia,0,3:03
8,Global,Global,9,Stuck with U (with Justin Bieber),"Ariana Grande, Justin Bieber",Stuck with U,0,3:48
9,Global,Global,10,Dance Monkey,Tones And I,Dance Monkey (Stripped Back) / Dance Monkey,0,3:29
10,Global,Global,11,GOOBA,6ix9ine,GOOBA,1,2:12
11,Global,Global,12,Blueberry Faygo,Lil Mosey,Certified Hitmaker,1,2:42
12,Global,Global,13,The Box,Roddy Ricch,Please Excuse Me For Being Antisocial,1,3:16
13,Global,Global,14,ily (i love you baby) (feat. Emilee),"Surf Mesa, Emilee",ily (i love you baby) (feat. Emilee),0,2:56
14,Global,Global,15,Break My Heart,Dua Lipa,Future Nostalgia,0,3:41
15,Global,Global,16,Supalonely,"BENEE, Gus Dapperton",STELLA & STEVE,1,3:43
16,Global,Global,17,Intentions (feat. Quavo),"Justin Bieber, Quavo",Changes,0,3:32
17,Global,Global,18,In Your Eyes,The Weeknd,After Hours,1,3:57
18,Global,Global,19,Sunday Best,Surfaces,Where the Light Is,0,2:38
19,Global,Global,20,Say So,Doja Cat,Hot Pink,1,3:57
20,Global,Global,21,Falling,Trevor Daniel,Nicotine,0,2:39
21,Global,Global,22,Savage Remix (feat. Beyoncé),"Megan Thee Stallion, Beyoncé",Savage Remix (feat. Beyoncé),1,4:02
22,Global,Global,23,Safaera,"Bad Bunny, Jowell & Randy, Nengo Flow",YHLQMDLG,1,4:55
23,Global,Global,24,Someone You Loved,Lewis Capaldi,Divinely Uninspired To A Hellish Extent,0,3:02
24,Global,Global,25,Yo Perreo Sola,Bad Bunny,YHLQMDLG,0,2:52
25,Global,Global,26,Circles,Post Malone,Hollywood's Bleeding,0,3:35
26,Global,Global,27,Say So (feat. Nicki Minaj),"Doja Cat, Nicki Minaj",Say So (feat. Nicki Minaj),1,3:26
27,Global,Global,28,Party Girl,StaySolidRocky,Party Girl,0,2:27
28,Global,Global,29,Watermelon Sugar,Harry Styles,Fine Line,0,2:54
29,Global,Global,30,goosebumps,Travis Scott,Birds In The Trap Sing McKnight,1,4:03
30,Global,Global,31,Tusa,"KAROL G, Nicki Minaj",Tusa,0,3:20
31,Global,Global,32,WHATS POPPIN,Jack Harlow,Sweet Action,1,2:19
32,Global,Global,33,Boss Bitch,Doja Cat,Boss Bitch,0,2:14
33,Global,Global,34,ROXANNE,Arizona Zervas,ROXANNE,1,2:43
34,Global,Global,35,SICKO MODE,Travis Scott,ASTROWORLD,1,5:12
35,Global,Global,36,Play Date,Melanie Martinez,Cry Baby (Deluxe Edition),1,2:59
36,Global,Global,37,Be Kind (with Halsey),"Marshmello, Halsey",Be Kind (with Halsey),0,2:52
37,Global,Global,38,Life Is Good (feat. Drake),"Future, Drake",High Off Life,1,3:57
38,Global,Global,39,HIGHEST IN THE ROOM,Travis Scott,HIGHEST IN THE ROOM,1,2:55
39,Global,Global,40,Breaking Me,"Topic, A7S",Breaking Me,0,2:46
40,Global,Global,41,Adore You,Harry Styles,Fine Line,0,3:27
41,Global,Global,42,Rojo,J Balvin,Colores,0,2:30
42,Global,Global,43,Before You Go,Lewis Capaldi,Divinely Uninspired To A Hellish Extent (Exten...,0,3:35
43,Global,Global,44,Memories,Maroon 5,Memories,0,3:09
44,Global,Global,45,After Party,Don Toliver,Heaven Or Hell,1,2:47
45,Global,Global,46,bad guy,Billie Eilish,"WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",0,3:14
46,Global,Global,47,Señorita,"Shawn Mendes, Camila Cabello",Shawn Mendes (Deluxe),0,3:10
47,Global,Global,48,Daechwita,Agust D,D-2,1,3:45
48,Global,Global,49,MAMACITA,"Black Eyed Peas, Ozuna, J. Rey Soul",MAMACITA,1,4:09
49,Global,Global,50,Favorito,Camilo,Por Primera Vez,0,3:29
50,Argentina,South America,1,Colocao,Nicki Nicole,Colocao,1,2:59
51,Argentina,South America,2,Favorito,Camilo,Por Primera Vez,0,3:29
52,Argentina,South America,3,PORFA,"Feid, Justin Quiles",FERXXO (VOL 1: M.O.R),0,3:52
53,Argentina,South America,4,Yo Perreo Sola,Bad Bunny,YHLQMDLG,0,2:52
54,Argentina,South America,5,"C.R.O: Bzrp Music Session, Vol. 29","Bizarrap, C.R.O","C.R.O: Bzrp Music Session, Vol. 29",0,2:26
55,Argentina,South America,6,Elegí (feat. Dímelo Flow),"Rauw Alejandro, Dalex, Lenny Tavárez, Dímelo Flow",Elegí (feat. Dímelo Flow),0,3:17
56,Argentina,South America,7,Rojo,J Balvin,Colores,0,2:30
57,Argentina,South America,8,Safaera,"Bad Bunny, Jowell & Randy, Nengo Flow",YHLQMDLG,1,4:55
58,Argentina,South America,9,Tattoo,Rauw Alejandro,Tattoo,0,3:22
59,Argentina,South America,10,Inolvidable,"Ovy On The Drums, Beéle",Inolvidable,0,3:45

In [28]:
uniq = data_df['Country'].unique()

In [52]:
data_df_filter = data_df[data_df['Country'].isin(uniq) & (data_df['Rank'] == 1) & (data_df['Country'] != 'Global')]

In [66]:
data_df_filter['Country'].unique()

array(['Argentina', 'Australia', 'Austria', 'Belgium', 'Bolivia',
       'Brazil', 'Bulgaria', 'Canada', 'Chile', 'Colombia', 'Costa Rica',
       'Czech Republic', 'Denmark', 'Dominican Republic', 'Ecuador',
       'El Salvador', 'Estonia', 'Finland', 'France', 'Germany', 'Greece',
       'Guatemala', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland',
       'India', 'Indonesia', 'Ireland', 'Israel', 'Italy', 'Japan',
       'Latvia', 'Lithuania', 'Luxembourg', 'Malaysia', 'Malta', 'Mexico',
       'Netherlands', 'New Zealand', 'Nicaragua', 'Norway', 'Panama',
       'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Romania',
       'Singapore', 'Slovakia', 'South Africa', 'Spain', 'Sweden',
       'Switzerland', 'Taiwan', 'Thailand', 'Turkey', 'United Kingdom',
       'United States', 'Uruguay', 'Vietnam'], dtype=object)

In [67]:
from geopy.geocoders import Nominatim
import folium

In [68]:
geolocator = Nominatim(user_agent='music_geocoder')

In [92]:
def geocoder_address(row):
    print(row['Country'])
    location = geolocator.geocode(row['Country'])
    print("location is",location)
    if location:
        print("Success")
        return location.latitude, location.longitude
    else:
        print("Failure")
        return None, None

In [93]:
data_df_filter['Latitude'], data_df_filter['Longitude'] = zip(*data_df_filter.apply(geocoder_address,axis=1))

Argentina
location is Argentina
Success
Australia
location is Australia
Success
Austria
location is Österreich
Success
Belgium
location is België / Belgique / Belgien
Success
Bolivia
location is Bolivia
Success
Brazil
location is Brasil
Success
Bulgaria
location is България
Success
Canada
location is Canada
Success
Chile
location is Chile
Success
Colombia
location is Colombia
Success
Costa Rica
location is Costa Rica
Success
Czech Republic
location is Česko
Success
Denmark
location is Danmark
Success
Dominican Republic
location is República Dominicana
Success
Ecuador
location is Ecuador
Success
El Salvador
location is El Salvador
Success
Estonia
location is Eesti
Success
Finland
location is Suomi / Finland
Success
France
location is France
Success
Germany
location is Deutschland
Success
Greece
location is Ελλάς
Success
Guatemala
location is Guatemala
Success
Honduras
location is Honduras
Success
Hong Kong
location is 香港 Hong Kong, 中国
Success
Hungary
location is Magyarország
Success
Iceland
location is Ísland
Success
India
location is India
Success
Indonesia
location is Indonesia
Success
Ireland
location is Éire / Ireland
Success
Israel
location is ישראל
Success
Italy
location is Italia
Success
Japan
location is 日本
Success
Latvia
location is Latvija
Success
Lithuania
location is Lietuva
Success
Luxembourg
location is Luxembourg, Canton Luxembourg, Lëtzebuerg
Success
Malaysia
location is Malaysia
Success
Malta
location is Malta
Success
Mexico
location is Ciudad de México, Cuauhtémoc, Ciudad de México, México
Success
Netherlands
location is Nederland
Success
New Zealand
location is New Zealand / Aotearoa
Success
Nicaragua
location is Nicaragua
Success
Norway
location is Norge
Success
Panama
location is Panamá
Success
Paraguay
location is Paraguay / Paraguái
Success
Peru
location is Perú
Success
Philippines
location is Pilipinas
Success
Poland
location is Polska
Success
Portugal
location is Portugal
Success
Romania
location is România
Success
Singapore
location is Singapore
Success
Slovakia
location is Slovensko
Success
South Africa
location is South Africa
Success
Spain
location is España
Success
Sweden
location is Sverige
Success
Switzerland
location is Schweiz/Suisse/Svizzera/Svizra
Success
Taiwan
location is 臺灣
Success
Thailand
location is ประเทศไทย
Success
Turkey
location is Türkiye
Success
United Kingdom
location is United Kingdom
Success
United States
location is United States
Success
Uruguay
location is Uruguay
Success
Vietnam
location is Việt Nam
Success

/var/folders/ry/r5ncj0b51qj5ykrwzk6w4t0r0000gn/T/ipykernel_15738/984944578.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df_filter['Latitude'], data_df_filter['Longitude'] = zip(*data_df_filter.apply(geocoder_address,axis=1))
/var/folders/ry/r5ncj0b51qj5ykrwzk6w4t0r0000gn/T/ipykernel_15738/984944578.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df_filter['Latitude'], data_df_filter['Longitude'] = zip(*data_df_filter.apply(geocoder_address,axis=1))

In [85]:
location = geolocator.geocode('Bolivia')

In [86]:
location.latitude

-17.0568696

In [87]:
location.longitude

-64.9912286

In [94]:
data_df_filter

,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration,Latitude,Longitude
50,Argentina,South America,1,Colocao,Nicki Nicole,Colocao,1,2:59,-34.996496,-64.967282
100,Australia,Australia,1,ROCKSTAR (feat. Roddy Ricch),"DaBaby, Roddy Ricch",BLAME IT ON BABY,1,3:01,-24.776109,134.755000
150,Austria,Europe,1,Roadrunner,Bonez MC,Roadrunner,0,2:29,47.593970,14.124560
200,Belgium,Europe,1,Blinding Lights,The Weeknd,After Hours,0,3:20,50.640281,4.666715
250,Bolivia,South America,1,Rojo,J Balvin,Colores,0,2:30,-17.056870,-64.991229
...,...,...,...,...,...,...,...,...,...,...
2900,Turkey,Europe,1,Spacejump,BEGE,Spacejump,0,1:58,38.959759,34.924965
2950,United Kingdom,Europe,1,ROCKSTAR (feat. Roddy Ricch),"DaBaby, Roddy Ricch",BLAME IT ON BABY,1,3:01,54.702354,-3.276575
3000,United States,North America,1,ROCKSTAR (feat. Roddy Ricch),"DaBaby, Roddy Ricch",BLAME IT ON BABY,1,3:01,39.783730,-100.445882
3050,Uruguay,South America,1,Favorito,Camilo,Por Primera Vez,0,3:29,-32.875555,-56.020153
3100,Vietnam,Asia,1,em bỏ hút thuốc chưa?,"Bich Phuong, traitimtrongvang",tâm trạng tan hơi chậm một chút,0,3:36,15.926666,107.965086

In [99]:
# Calculate the map center based on the points
map_center = [data_df_filter['Latitude'].mean(), data_df_filter['Longitude'].mean()]

In [100]:
map_center

[25.846290994354842, 5.459933822174835]

In [101]:
mymap = folium.Map(location = map_center, zoom_start = 4)

In [126]:
for index, row in data_df_filter.iterrows():
    
    if(row['Latitude'] and row['Longitude']):
        
        popup_text = f"""
        <b><span style='color:red;'>{row['Title']}</span></b>  
        <br>by <span style='color:blue;'>{row['Artists']}</span>  
        <br>in album <b>{row['Album']}</b>
        """
            
        folium.Marker(
            [row['Latitude'], row['Longitude']] , 
            icon=folium.Icon(color='blue', icon='music', prefix='fa'), 
            popup=folium.Popup(popup_text, max_width=300)
        ).add_to(mymap)

In [127]:
mymap.save('music_geocode.html')

In [ ]:
# folium.Marker(location=[0,20], icon=folium.Icon(color='lightgray', icon='home', prefix='fa')).add_to(m)